### ISSUE TITLE
unable to import tkinter in windows machine

### ISSUE THREAD

**Issue by rohith5429** [AcademySoftwareFoundation/xstudio#111]
unable to import tkinter library in windows

Xstudios version: 3.10

```
[2024-08-17 15:06:34.751] [xstudio] [info] XStudio logging started.
[2024-08-17 15:06:34.927] [xstudio] [info] API enabled on 127.0.0.1:45500, session name default0
[OpenColorIO Info]: Color management disabled. (Specify the $OCIO environment variable to enable.)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x6a79ad438), parent's thread is QThread(0x1bcdf451a30), current thread is QThread(0x1bcdf785690)
qrc:/widgets/XsLoopWidget.qml:12: TypeError: Value is undefined and could not be converted to an object
qrc:/widgets/XsLoopWidget.qml:12: TypeError: Cannot read property 'icon' of undefined
[2024-08-17 15:06:35.689] [info] XStudio UI launched.
xStudio - console
Use XSTUDIO object for api access.
>>> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Dev\Desktop\xstudio_install\python\tkinter\__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by nsankar90** [comment]
All the modules are working fine except the Tkinter. If we want to take some user inputs what shall we use?
